name: Docker Image CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/portfolio .

      - name: List the Docker images
        run: docker images

      - name: Push to Dockerhub
        run: docker push ${{secrets.DOCKER_USERNAME}}/portfolio
