name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js with version 20.x
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Archive the project folder as portfolio-development-server.zip
      - name: Archive project folder
        run: zip -r portfolio-development-server.zip .

      # Copy the archived folder to the EC2 instance
      - name: Transfer to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "portfolio-development-server.zip"
          target: "~/"

      # SSH into EC2 and deploy or restart services
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            unzip ~/portfolio-development-server.zip -d ~/portfolio-development-server
            cd ~/portfolio-development-server
            npm install
            pm2 restart all  # Example: Restart PM2 services if you're using it
